from dotenv import dotenv_values

config = dotenv_values(".env")

SECRET_KEY = config["SECRET_KEY"]
ALGORITHM = config["ALGORITHM"]
MONGODB_URL_KEY = config["MONGODB_URL_KEY"]
DATABASE_NAME = config["DATABASE_NAME"]
USER_COLLECTION_NAME = config["USER_COLLECTION_NAME"]
EMBEDDING_COLLECTION_NAME = config["EMBEDDING_COLLECTION_NAME"]

SIMILARITY_THRESHOLD = 0.75
DETECTOR_BACKEND = "mtcnn"
ENFORCE_DETECTION = False
EMBEDDING_MODEL_NAME = "Facenet"
